base:
  project_root: "/Projects/media_server"
  logs_folder: "logs"
  
  qbitorrent_host: "http://localhost:8080"
  qbitorrent_username: "krandle"
  qbitorrent_password: !ENV QBITORRENT_PASSWORD
  qbitorrent_port: 8080

  torrentfiles: "/torrentfiles"
  completed: "/completed"
  dropbox: "/dropbox"
    
dev:
  user: "krandle"
  home: "/Users/krandle"
  file_server: "/Users/krandle/krandle_handle_dev"
  torrentfiles: "/Users/krandle/krandle_handle_dev/torrentfiles"
  completed: "/Users/krandle/krandle_handle_dev/completed"
  dropbox: "/Users/krandle/krandle_handle_dev/dropbox"
  log: "/User/krandle/krandle_handle_dev/torrent_downloader.log"

prod:
  user: "kr"
  home: "/Users/kr"
  file_server: "/Volumes/krandle_handle"
  torrentfiles: "/Volumes/krandle_handle/torrentfiles"
  completed: "/Volumes/krandle_handle/completed"
  dropbox: "/downloads"
  log: "/Volumes/krandle_handle/torrent_downloader.log"