base:
  project_root: "/usr/local/srv/dev/projects/media_server"
  logs_folder: "/usr/local/srv/dev/logs"
  


  media_root: "/usr/local/srv/media"
  torrentfiles: "/usr/local/srv/media/torrentfiles"
  completed: "/usr/local/srv/media/completed"
  dropbox: "/usr/local/srv/media/dropbox"

dev:
  user: "krandle"
  home: "/Users/krandle"
  file_server: "/usr/local/srv/dev/storage"
  torrentfiles: "/usr/local/srv/dev/storage/torrentfiles"
  completed: "/usr/local/srv/dev/storage/completed"
  dropbox: "/downloads"
  dropboxactual: "/usr/local/srv/dev/storage/dropbox"
  log: "/usr/local/srv/dev/logs/qbitorrent_dev/torrent_downloader.log"
  log_level: "DEBUG"
  qbitorrent_host: "http://localhost:8081"
  qbitorrent_username: "krandle"
  qbitorrent_password: !ENV QBITORRENT_PASSWORD
  qbitorrent_port: 8081
  hitAndRunTime: 300

prod:
  user: "kr"
  home: "/Users/kr"
  file_server: "/usr/local/srv/dev/scripts"
  torrentfiles: "/usr/local/srv/media/torrentfiles"
  completed: "/usr/local/srv/media/completed"
  dropbox: "/downloads"
  dropboxactual: "/usr/local/srv/media/dropbox"
  log: "/usr/local/srv/dev/logs/qbitorrent_prod/torrent_downloader.log"
  log_level: "INFO"
  qbitorrent_host: "http://localhost:8080"
  qbitorrent_username: "krandle"
  qbitorrent_password: !ENV QBITORRENT_PASSWORD
  qbitorrent_port: 8080
  hitAndRunTime: 950400

docker:
  dev:
    torrent_app:
      service: "qbittorrent_dev"
      network: "qbittorrent_dev_net"
      compose_path: "/usr/local/srv/dev/projects/media_server/docker-compose.yml"
      image: "binhex/arch-qbittorrentvpn"
      container_name: "qbittorrent_dev"
      network_mode: "bridge"
      data_dir: "/usr/local/srv/dev/storage/dropbox"
      config_dir: "/usr/local/srv/dev/configs/qbittorrent_dev"
      vpn_enabled: false  # No VPN in dev for debugging
      port: "8081"
      ports:
        - "8081:8081"  # Different port to avoid conflicts
      restart_policy: "unless-stopped"
    portainer:
      service: "portainer_dev"
      network: "qbittorrent_dev_net"
      compose_path: "/usr/local/srv/dev/projects/media_server/docker-compose.yml"
      image: "portainer/portainer-ce"
      container_name: "portainer_dev"
      network_mode: "bridge"
      ports:
        - "9001:9000"
        - "9444:9443"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/usr/local/srv/dev/configs/portainer_dev:/data"
      restart_policy: "unless-stopped"
    nextcloud:
      service: "nextcloud_dev"
      network: "nextcloud_dev_net"
      compose_path: "/usr/local/srv/dev/projects/media_server/docker-compose.yml"
      image: "nextcloud"
      container_name: "nextcloud_dev"
      network_mode: "bridge"
      ports:
        - "8082:80"
      volumes:
        - "/usr/local/srv/dev/storage/nextcloud:/var/www/html"  # Nextcloud app storage
        - "/usr/local/srv/dev/storage/nextcloud_data:/var/www/html/data"  # Nextcloud data
        - "/usr/local/srv/dev/storage/torrentfiles:/external_media/torrentfiles:ro"
        - "/usr/local/srv/dev/storage/completed:/external_media/completed:ro"
      environment:
        - NEXTCLOUD_ADMIN_USER=admin
        - NEXTCLOUD_ADMIN_PASSWORD=1022
        - NEXTCLOUD_DATA_DIR=/var/www/html/data
      restart_policy: "unless-stopped"
    nextcloud_db:
      service: "nextcloud_db_dev"
      network: "nextcloud_dev_net"
      compose_path: "/usr/local/srv/dev/projects/media_server/docker-compose.yml"
      image: "mariadb"
      container_name: "nextcloud_db_dev"
      network_mode: "bridge"
      environment:
        - MYSQL_ROOT_PASSWORD=your_root_password
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=nextcloud
        - MYSQL_PASSWORD=your_secure_password
      volumes:
        - "/usr/local/srv/dev/storage/nextcloud_db_dev:/var/lib/mysql"
      restart_policy: "unless-stopped"
    redis:
      image: "redis:alpine"
      service: "redis_dev"
      container_name: "nextcloud_redis_dev"
      restart_policy: "unless-stopped"
      network: "nextcloud_dev_net"


  prod:
    torrent_app:
      service: "qbittorrent_prod"
      network: "qbittorrent_prod_net"
      compose_path: "/usr/local/srv/dev/scripts/media_server/docker-compose.yml"
      image: "binhex/arch-qbittorrentvpn"
      container_name: "qbittorrent"
      network_mode: "bridge"
      data_dir: "/usr/local/srv/vol/srv-disk1_14_25/dropbox"
      config_dir: "/usr/local/srv/dev/configs/qbittorrent"
      vpn_enabled: true
      vpn_provider: "pia"
      vpn_user: !ENV VPN_USER
      vpn_pass: !ENV VPN_PASS
      strict_port_forward: "yes"
      port: "8080"
      ports:
        - "8080:8080"
      restart_policy: "unless-stopped"
    portainer:
      service: "portainer_prod"
      network: "qbittorrent_prod_net"
      compose_path: "/usr/local/srv/dev/scripts/media_server/docker-compose.yml"
      image: "portainer/portainer-ce"
      container_name: "portainer"
      network_mode: "bridge"
      ports:
        - "9000:9000"
        - "9443:9443"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/usr/local/srv/dev/configs/portainer:/data"
      restart_policy: "unless-stopped"
    nextcloud:
      service: "nextcloud"
      network: "nextcloud_net"
      compose_path: "/usr/local/srv/dev/scripts/media_server/docker-compose.yml"
      image: "nextcloud"
      container_name: "nextcloud"
      network_mode: "bridge"
      ports:
        - "8083:80"
      volumes:
        - "/usr/local/srv/media/nextcloud:/var/www/html"
        - "/usr/local/srv/media/nextcloud_data:/var/www/html/data"
        - "/usr/local/srv/media/torrentfiles:/external_media/torrentfiles:ro"
        - "/usr/local/srv/media/completed:/external_media/completed:ro"
      environment:
        - NEXTCLOUD_ADMIN_USER=admin
        - NEXTCLOUD_ADMIN_PASSWORD=your_secure_password
        - NEXTCLOUD_DATA_DIR=/var/www/html/data
      restart_policy: "unless-stopped"
    nextcloud_db:
      service: "nextcloud_db"
      network: "nextcloud_net"
      compose_path: "/usr/local/srv/dev/scripts/media_server/docker-compose.yml"
      image: "mariadb"
      container_name: "nextcloud_db"
      network_mode: "bridge"
      environment:
        - MYSQL_ROOT_PASSWORD=your_root_password
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=nextcloud
        - MYSQL_PASSWORD=your_secure_password
      volumes:
        - "/usr/local/srv/media/nextcloud_db:/var/lib/mysql"
      restart_policy: "unless-stopped"
    redis:
      image: "redis:alpine"
      container_name: "nextcloud_redis"
      restart_policy: "unless-stopped"
      network: "nextcloud_net"
