# config.yaml

environment: dev  # Switch between "dev" and "prod"

base:
  project_root: "/Projects/media_server"
  logs_folder: "logs"
  seedbox_address: "ant.seedhost.eu"
  seedbox_username: "krandlehandle"
  ssh_key: "/.ssh/id_rsa"
  rtorrent_username: "krandlehandle"
  rtorrent_password: "!ENV RTORRENT_PASSWORD"
  rtorrent_remote_host: "127.0.0.1"
  rtorrent_xml_port: "5060"
  dropzone: "dropbox"
  seedbox_root_path: "/home22/krandlehandle"
dev:
  host: "localhost"
  user: "krandle"
  home: "/Users/krandle"
  file_server: "/Users/krandle/krandle_handle_dev"


prod:
  host: "192.168.0.69"
  user: "kr"
  home: "/Users/kr"
  file_server: "/Volumes/krandle_handle"


