base:
  project_root: "/usr/local/srv/dev/projects/media_server"
  logs_folder: "/usr/local/srv/dev/logs"
  


  media_root: "/usr/local/srv/media"
  torrentfiles: "/usr/local/srv/media/torrentfiles"
  completed: "/usr/local/srv/media/completed"
  dropbox: "/usr/local/srv/media/dropbox"

dev:
  user: "krandle"
  home: "/Users/krandle"
  file_server: "/usr/local/srv/dev/storage"
  torrentfiles: "/usr/local/srv/dev/storage/torrentfiles"
  completed: "/usr/local/srv/dev/storage/completed"
  dropbox: "/downloads"
  dropboxactual: "/usr/local/srv/dev/storage/dropbox"
  log: "/usr/local/srv/dev/logs/qbitorrent_dev/torrent_downloader.log"
  log_level: "DEBUG"
  qbitorrent_host: "http://localhost:8081"
  qbitorrent_username: "krandle"
  qbitorrent_password: !ENV QBITORRENT_PASSWORD
  qbitorrent_port: 8081
  hitAndRunTime: 300

prod:
  user: "kr"
  home: "/Users/kr"
  file_server: "/usr/local/srv/dev/scripts"
  torrentfiles: "/usr/local/srv/media/torrentfiles"
  completed: "/usr/local/srv/media/completed"
  dropbox: "/downloads"
  dropboxactual: "/usr/local/srv/media/dropbox"
  log: "/usr/local/srv/dev/logs/qbitorrent_prod/torrent_downloader.log"
  log_level: "INFO"
  qbitorrent_host: "http://localhost:8080"
  qbitorrent_username: "krandle"
  qbitorrent_password: !ENV QBITORRENT_PASSWORD
  qbitorrent_port: 8080
  hitAndRunTime: 950400

docker:
  dev:
    torrent_app:
      service: "qbittorrent_dev"
      network: "qbittorrent_dev_net"
      compose_path: "/usr/local/srv/dev/projects/media_server/docker-compose.yml"
      image: "binhex/arch-qbittorrentvpn"
      container_name: "qbittorrent_dev"
      network_mode: "bridge"
      data_dir: "/usr/local/srv/dev/storage/dropbox"
      config_dir: "/usr/local/srv/dev/configs/qbittorrent_dev"
      vpn_enabled: false  # No VPN in dev for debugging
      port: "8081"
      ports:
        - "8081:8081"  # Different port to avoid conflicts
      restart_policy: "unless-stopped"

  prod:
    torrent_app:
      service: "qbittorrent_prod"
      network: "qbittorrent_prod_net"
      compose_path: "/usr/local/srv/dev/scripts/media_server/docker-compose.yml"
      image: "binhex/arch-qbittorrentvpn"
      container_name: "qbittorrent"
      network_mode: "bridge"
      data_dir: "/usr/local/srv/media"
      config_dir: "/usr/local/srv/dev/configs/qbittorrent"
      vpn_enabled: true
      vpn_provider: "PIA"
      vpn_user: !ENV VPN_USER
      vpn_pass: !ENV VPN_PASS
      port: "8080"
      ports:
        - "8080:8080"
      restart_policy: "unless-stopped"