base:
  project_root: "/Projects/media_server"
  logs_folder: "logs"
  
  qbitorrent_host: "http://localhost:9091"
  qbitorrent_username: "krandle"
  qbitorrent_password: !ENV QBITORRENT_PASSWORD
  qbitorrent_port: 9091

  torrentfiles: "/torrentfiles"
  completed: "/completed"
  dropbox: "/dropbox"

  
dev:
  user: "krandle"
  home: "/Users/krandle"
  file_server: "/Users/krandle/krandle_handle_dev"

prod:
  user: "kr"
  home: "/Users/kr"
  file_server: "/Volumes/krandle_handle"