version: "3.9"
services:
  qbittorrent:
    image: "binhex/arch-qbittorrentvpn"
    container_name: "qbittorrent_dev"
    network_mode: "bridge"
    environment:
      - VPN_ENABLED=no
      - VPN_PROV=
      - VPN_USER=
      - VPN_PASS=
    volumes:
      - /usr/local/srv/dev/configs/qbittorrent:/config
      - /usr/local/srv/dev/storage/dropbox:/downloads
    ports:
      - 8081:8080
    restart: unless-stopped
